In [4]:
import numpy as np
import pandas as pd

In [5]:
print(pd.__version__)

3.0.2

In [6]:
print(np.__version__)

2.4.4

In [7]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [8]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [9]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [10]:
pd.merge(employees , salaries)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

## Group by aggregation

In [11]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

In [14]:
df = pd.DataFrame(data)

In [15]:
df.head()

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05

In [19]:
df.groupby("Category")["Sales"].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

In [22]:
abc  = df.groupby(["Category" , "Store"])["Sales"].sum()
abc

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [23]:
df["Sales"].mean()

np.float64(187.5)

In [24]:
df["Sales"].median()

np.float64(190.0)

In [25]:
df["Sales"].count()

np.int64(8)

In [26]:
df["Sales"].std()

np.float64(66.06274074155351)

In [27]:
df["Sales"].mode()

0    200
Name: Sales, dtype: int64

In [28]:
df["Sales"].agg(["sum" , "min" , "max" , "mean" , "median"])

sum       1500.0
min        100.0
max        300.0
mean       187.5
median     190.0
Name: Sales, dtype: float64

In [29]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    333     22   John  January      Q1
1  2023-01-02       B   West    624     74   Mary  January      Q1
2  2023-01-03       C  North    594     27    Bob  January      Q1
3  2023-01-04       D  South    212     53  Alice  January      Q1
4  2023-01-05       A   East    652     44   John  January      Q1
5  2023-01-06       B   West    747     18   Mary  January      Q1
6  2023-01-07       C  North    917     66    Bob  January      Q1
7  2023-01-08       D  South    428     89  Alice  January      Q1
8  2023-01-09       A   East    981     29   John  January      Q1
9  2023-01-10       B   West    900     19   Mary  January      Q1
10 2023-01-11       C  North    490     46    Bob  January      Q1
11 2023-01-12       D  South    288     22  Alice  January      Q1
12 2023-01-13       A   East    699     28   John  January      Q1
13 2023-01-14       B   West    191     30   Mary  January      Q1
14 2023-01-15       C  North    235     92    Bob  January      Q1
15 2023-01-16       D  South    948     72  Alice  January      Q1
16 2023-01-17       A   East    806     52   John  January      Q1
17 2023-01-18       B   West    699     34   Mary  January      Q1
18 2023-01-19       C  North    414     82    Bob  January      Q1
19 2023-01-20       D  South    194     92  Alice  January      Q1

In [31]:
pd.pivot_table(df , values="Sales" , index="Region" , columns="Product")

Product      A      B      C      D
Region
East     694.2    NaN    NaN    NaN
North      NaN    NaN  530.0    NaN
South      NaN    NaN    NaN  414.0
West       NaN  632.2    NaN    NaN

In [32]:
pd.pivot_table(df , values="Units" , index="Region" , columns="Product")

Product     A     B     C     D
Region
East     35.0   NaN   NaN   NaN
North     NaN   NaN  62.6   NaN
South     NaN   NaN   NaN  65.6
West      NaN  35.0   NaN   NaN

In [33]:
pd.crosstab(df["Sales"] , df["Product"])

Product  A  B  C  D
Sales
191      0  1  0  0
194      0  0  0  1
212      0  0  0  1
235      0  0  1  0
288      0  0  0  1
333      1  0  0  0
414      0  0  1  0
428      0  0  0  1
490      0  0  1  0
594      0  0  1  0
624      0  1  0  0
652      1  0  0  0
699      1  1  0  0
747      0  1  0  0
806      1  0  0  0
900      0  1  0  0
917      0  0  1  0
948      0  0  0  1
981      1  0  0  0

In [34]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [35]:
df.shape

(20, 8)

In [36]:
df.size

160

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     20 non-null     datetime64[us]
 1   Product  20 non-null     str
 2   Region   20 non-null     str
 3   Sales    20 non-null     int32
 4   Units    20 non-null     int32
 5   Rep      20 non-null     str
 6   Month    20 non-null     str
 7   Quarter  20 non-null     str
dtypes: datetime64[us](1), int32(2), str(5)
memory usage: 1.2 KB

In [38]:
df.describe()

                      Date       Sales      Units
count                   20   20.000000  20.000000
mean   2023-01-10 12:00:00  567.600000  49.550000
min    2023-01-01 00:00:00  191.000000  18.000000
25%    2023-01-05 18:00:00  321.750000  27.750000
50%    2023-01-10 12:00:00  609.000000  45.000000
75%    2023-01-15 06:00:00  761.750000  72.500000
max    2023-01-20 00:00:00  981.000000  92.000000
std                    NaN  269.846038  26.270806

In [39]:
df.head()

        Date Product Region  Sales  Units    Rep    Month Quarter
0 2023-01-01       A   East    333     22   John  January      Q1
1 2023-01-02       B   West    624     74   Mary  January      Q1
2 2023-01-03       C  North    594     27    Bob  January      Q1
3 2023-01-04       D  South    212     53  Alice  January      Q1
4 2023-01-05       A   East    652     44   John  January      Q1

In [40]:
df.tail()

         Date Product Region  Sales  Units    Rep    Month Quarter
15 2023-01-16       D  South    948     72  Alice  January      Q1
16 2023-01-17       A   East    806     52   John  January      Q1
17 2023-01-18       B   West    699     34   Mary  January      Q1
18 2023-01-19       C  North    414     82    Bob  January      Q1
19 2023-01-20       D  South    194     92  Alice  January      Q1

In [41]:
df.sample(5)

         Date Product Region  Sales  Units    Rep    Month Quarter
7  2023-01-08       D  South    428     89  Alice  January      Q1
11 2023-01-12       D  South    288     22  Alice  January      Q1
17 2023-01-18       B   West    699     34   Mary  January      Q1
4  2023-01-05       A   East    652     44   John  January      Q1
12 2023-01-13       A   East    699     28   John  January      Q1

In [46]:
df["A"] = 10

In [44]:
df.head()

        Date Product Region  Sales  Units    Rep    Month Quarter   A
0 2023-01-01       A   East    333     22   John  January      Q1  10
1 2023-01-02       B   West    624     74   Mary  January      Q1  10
2 2023-01-03       C  North    594     27    Bob  January      Q1  10
3 2023-01-04       D  South    212     53  Alice  January      Q1  10
4 2023-01-05       A   East    652     44   John  January      Q1  10

In [47]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [48]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [51]:
df1['D'] = df1['B'].apply(lambda x : x ** 2)

In [52]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500